# Generated by Django 4.2.9 on 2024-02-24 01:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestType',
            fields=[
                ('questTypeID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('societyID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=150)),
                ('numberOfMembers', models.PositiveBigIntegerField(default=0)),
                ('societyXP', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Societies',
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('questID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('task', models.CharField(default=0, max_length=150)),
                ('reward', models.PositiveBigIntegerField(default=0)),
                ('state', models.BooleanField(default=False)),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.location')),
                ('questTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.questtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membershipID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('since', models.DateField(auto_now_add=True)),
                ('state', models.BooleanField(default=False)),
                ('societyID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapi.society')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
