# Generated by Django 4.2.9 on 2024-02-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
