# Generated by Django 4.2.9 on 2024-02-22 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0003_society_userprofile_remove_quest_questtypeid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('leaderboardID', models.BigAutoField(primary_key=True, serialize=False)),
                ('leaderboardName', models.CharField(max_length=50)),
                ('leaderboardDescription', models.CharField(max_length=150)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RewardQuest',
            fields=[
                ('rewardQuestID', models.BigAutoField(primary_key=True, serialize=False)),
                ('currency', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='quest',
            name='userID',
        ),
        migrations.AddField(
            model_name='society',
            name='numberOfMembers',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='society',
            name='societyXP',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserLeaderboard',
            fields=[
                ('userLeaderboardID', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('leaderboardID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapi.leaderboard')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RewardLeaderboard',
            fields=[
                ('rewardLeaderboardID', models.BigAutoField(primary_key=True, serialize=False)),
                ('rankingCondition', models.IntegerField()),
                ('currency', models.IntegerField()),
                ('leaderboardID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapi.leaderboard')),
            ],
        ),
        migrations.CreateModel(
            name='QuestType',
            fields=[
                ('questTypeID', models.BigAutoField(primary_key=True, serialize=False)),
                ('typeName', models.CharField(max_length=80)),
                ('typeDescription', models.CharField(max_length=150)),
                ('rewardQuestID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapi.rewardquest')),
            ],
        ),
    ]
