# Generated by Django 5.0.1 on 2024-02-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0003_remove_image_id_image_image_alter_image_imageid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
