# Generated by Django 4.2.9 on 2024-02-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_leaderboard_rewardquest_remove_quest_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='Task',
        ),
        migrations.RemoveField(
            model_name='questtype',
            name='rewardQuestID',
        ),
        migrations.AddField(
            model_name='quest',
            name='reward',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='startDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='questtype',
            name='typeDescription',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='society',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.DeleteModel(
            name='RewardQuest',
        ),
        migrations.DeleteModel(
            name='userProfile',
        ),
        migrations.AddField(
            model_name='quest',
            name='task',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
