# Generated by Django 4.2.9 on 2024-02-22 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0005_remove_userprofile_user_remove_quest_task_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default='', max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membershipID', models.BigAutoField(primary_key=True, serialize=False)),
                ('since', models.DateField(auto_now_add=True)),
                ('state', models.BooleanField(default=False)),
                ('societyID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myapi.society')),
            ],
        ),
    ]
