# Generated by Django 4.2.9 on 2024-02-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Player', 'Player'), ('GameKeeper', 'GameKeeper'), ('Developer', 'Developer')], default='Player', max_length=20),
        ),
        migrations.AlterField(
            model_name='quest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
