# Generated by Django 4.2.10 on 2024-02-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='imgURL',
            field=models.CharField(default='', max_length=150),
        ),
    ]
