# Generated by Django 4.2.9 on 2024-02-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_remove_userleaderboard_userid_membership_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userID',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='userID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='myapi.userprofile'),
            preserve_default=False,
        ),
    ]
