# Generated by Django 4.2.9 on 2024-02-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_userprofile_role_alter_quest_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
