# Generated by Django 4.2.9 on 2024-02-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_quest_imgurl'),
        ('myapi', '0008_userprofile_streak_alter_userprofile_is_active'),
    ]

    operations = [
    ]
