# Generated by Django 4.2.7 on 2024-03-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0008_alter_quest_date_made_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="date_made_active",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
