# Generated by Django 4.2.9 on 2024-02-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_alter_userprofile_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='userID',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=True,
        ),
    ]
