# Generated by Django 4.2.9 on 2024-02-29 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_alter_quest_imgurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestSubmission',
            fields=[
                ('questsubID', models.BigAutoField(primary_key=True, serialize=False)),
                ('imgURL', models.CharField(max_length=200)),
                ('info', models.CharField(default='The task has been completed', max_length=150)),
                ('verified', models.BooleanField(default=False)),
                ('questID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.quest')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
