# Generated by Django 4.2.9 on 2024-02-29 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_questsubmission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questsubmission',
            old_name='userID',
            new_name='user',
        ),
    ]
