# Generated by Django 4.2.9 on 2024-03-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_rename_userid_questsubmission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questsubmission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='society',
            name='societyXP',
        ),
        migrations.AlterField(
            model_name='quest',
            name='task',
            field=models.CharField(default='', max_length=150),
        ),
    ]
