# Generated by Django 4.2.9 on 2024-03-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_remove_society_societyxp_alter_quest_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='societyXP',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
