# Generated by Django 4.2.9 on 2024-03-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_remove_questsubmission_user_remove_society_societyxp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='society',
            name='societyXP',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
