# Generated by Django 4.2.9 on 2024-03-08 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_society_societyxp_alter_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='questsubmission',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
