# Generated by Django 4.2.9 on 2024-02-22 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_alter_membership_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='society',
            options={'verbose_name_plural': 'Societies'},
        ),
        migrations.RenameField(
            model_name='quest',
            old_name='quest_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='questtype',
            old_name='typeDescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='questtype',
            old_name='typeName',
            new_name='name',
        ),
    ]
