# Generated by Django 4.2.9 on 2024-03-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_questsubmission_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='border',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
