# Generated by Django 5.0.3 on 2024-03-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0016_questsubmission_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="date_made_active",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
