# Generated by Django 4.2.9 on 2024-02-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_alter_society_options_rename_quest_name_quest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='name',
            field=models.CharField(default='Test_society Membership', max_length=80),
            preserve_default=False,
        ),
    ]
