# Generated by Django 5.0.1 on 2024-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapi", "0016_questsubmission_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="questsubmission",
            name="rejected",
            field=models.BooleanField(default=False),
        ),
    ]
