# Generated by Django 4.2.9 on 2024-02-23 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_membership_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='XP',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
