# Generated by Django 4.2.9 on 2024-03-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_userprofile_border'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='imgURL',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
