# Generated by Django 4.2.9 on 2024-02-23 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0018_userprofile_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='rewardleaderboard',
            name='leaderboardID',
        ),
        migrations.RemoveField(
            model_name='userleaderboard',
            name='leaderboardID',
        ),
        migrations.AlterField(
            model_name='questtype',
            name='name',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='RewardLeaderboard',
        ),
        migrations.DeleteModel(
            name='UserLeaderboard',
        ),
    ]
