# Generated by Django 4.2.9 on 2024-02-23 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0019_friend_remove_rewardleaderboard_leaderboardid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='questTypeID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='myapi.questtype'),
            preserve_default=False,
        ),
    ]
