# Generated by Django 4.2.9 on 2024-02-23 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_quest_questtypeid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationID', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='quest',
            name='questTypeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.questtype'),
        ),
    ]
