# Generated by Django 4.2.9 on 2024-02-23 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_location_alter_quest_questtypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='locationID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.location'),
            preserve_default=False,
        ),
    ]
